baseURL = "https://devopsschmiede.github.io"
languageCode = "en-us"
title = "DevOps Schmiede"
theme = "devopsschmiede"
defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
description = "The DevOps Schmiede is ..."
[languages.de]
contentDir = "content/de"
languageName = "Deutsch"
weight = 2
description = "Die DevOps Schmiede ist ..."

[taxanomies]
tag = "tags"
category = "categories"

[markup.highlight]
linenos = true
anchorLineNos = true
lineanchors = "L"
style = "dracula"
[markup.goldmark.renderer]
unsafe = true

[module]
[[module.mounts]]
source = "./node_modules/@fontsource/saira/files"
target = "static/css/files"
[[module.mounts]]
source = "./node_modules/vanilla-tilt/dist"
target = "static/js/files"
includeFiles = ["vanilla-tilt.min.js"]
[[module.mounts]]
source = "./themes/devopsschmiede/assets/images/"
target = "static/images"

[outputs]
home = ["HTML", "RSS", "JSON"]
