baseURL = "https://devops-schmiede.de/"
languageCode = "en-us"
title = "DevOps Schmiede"
theme = "devopsschmiede"
description = "DevOps Schmiede"
defaultContentLanguage = "en"

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1
[languages.de]
contentDir = "content/de"
languageName = "Deutsch"
weight = 1

[taxanomies]
tag = "tags"
category = "categories"

[markup.highlight]
linenos = true
anchorLineNos = true
lineanchors = "L"
style = "dracula"

[module]
[[module.mounts]]
source = "./node_modules/@fontsource/saira/files"
target = "static/css/files"
